/**
 * GLOBALS
 */
let canvas = document.getElementById("myCanvas") as HTMLCanvasElement,
    ctx = canvas.getContext("2d"),
    colour = "#0095DD",
    font = "20px VT323",
    ballRadius = 7,
    x = canvas.width / 2,
    y = canvas.height - 30,
    dx = 2,
    dy = -2,
    paddleHeight = 7,
    paddleWidth = 75,
    paddleX = (canvas.width - paddleWidth) / 2,
    rightPressed = false,
    leftPressed = false,
    brickRowCount = 5,
    brickColumnCount = 3,
    brickWidth = 75,
    brickHeight = 20,
    brickPadding = 2,
    brickOffsetTop = 30,
    brickOffsetLeft = 15,
    score = 0,
    lives = 3,
    gameOver = false,
    win = false,
    destroyCount = 0,
    lifeCount = 0;

export const globals = {
    canvas,
    ctx,
    colour,
    font,
    ballRadius,
    x,
    y,
    dx,
    dy,
    paddleHeight,
    paddleWidth,
    paddleX,
    rightPressed,
    leftPressed,
    brickRowCount,
    brickColumnCount,
    brickWidth,
    brickHeight,
    brickPadding,
    brickOffsetTop,
    brickOffsetLeft,
    score,
    lives,
    gameOver,
    win,
    destroyCount,
    lifeCount
}